spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
    username: demouser
    password: demopass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  context-path: /monitoring

spring-rest:
  class:
    size: 6
    name: spring-class
    description: My class name is ${spring-rest.class.name} and size is ${spring-rest.class.size}
    servers:
      - server1.com
      - server2.com
      - server3.com



