spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
    username: demouser
    password: demopass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

