spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  context-path: /monitoring

spring-rest:
  class:
    size: 6
    name: spring-class
    description: My class name is ${spring-rest.class.name} and size is ${spring-rest.class.size}
    servers:
      - server1.com
      - server2.com
      - server3.com

---
spring:
  profiles: prod

  datasource:
    username: produser
    password: prodpass

---
spring:
  profiles: test

  datasource:
    username: ${DATABASE_USERNAME:demouser}
    password: ${DATABASE_PASSWORD:demopass}




